' Documentazione: https://plantuml.com/class-diagram
  
@startuml
' START STYLE
skinparam {
    monochrome true
    classBackgroundColor white
    noteBackgroundColor white
    classAttributeIconSize 0
}
hide circle
' END STYLE

title MiniGame: Text-Dungeon\n

hide members

class GeneraPietra {
    - genera: List<Function<Float, Pietra>>
    - pietra: Pietra
    - rand: Float
    - instance{static}: GeneraPietra
    + getInstance(){static}: GeneraPietra
    + getPietra(): Pietra
    - calcolaProbabilita(): float
    + getRand(): float
}
show GeneraPietra members

class Partita

interface Pietra <<interface>> {
    + getTipo(): String
    + moltiplicatoreDanno(): float
}
show Pietra members

class PietraGrigia implements Pietra {
    + getTipo(): String
    + moltiplicatoreDanno(): float
}
show PietraGrigia members

class PietraBianca implements Pietra {
    + getTipo(): String
    + moltiplicatoreDanno(): float
    - probabilitaAumentoDanno(): boolean
}
show PietraBianca members

class PietraNera implements Pietra {
    + getTipo(): String
    + moltiplicatoreDanno(): float
    - probabilitaAumentoDanno(): boolean
}
show PietraNera members

interface Arma <<interface>> {
    + getTipo(): String
    + getDanno(): float
}
show Arma members

class GeneraArma {
    - generaPietra: GeneraPietra
    - genera: Map<Integer, Function<Pietra, Arma>>
    - instance{static}: GeneraArma
    - GeneraArma()
    + getInstance(){static}: GeneraArma
    + getArma(int): Arma
}
show GeneraArma members

class Ascia implements Arma {
    - pietra: Pietra
    - danno: float
    + getTipo(): String
    + getDanno(): float
    - generaDanno(): float
}
show Ascia members

class Mannaia implements Arma {
    - pietra: Pietra
    - danno: float
    + getTipo(): String
    + getDanno(): float
    - generaDanno(): float
}
show Mannaia members


class Spada implements Arma {
    - pietra: Pietra
    - danno: float
    + getTipo(): String
    + getDanno(): float
    - generaDanno(): float
}
show Spada members

class Giocatore {
    - vita: float
    - arma: Arma
    - instance{static}: Giocatore 
    - Giocatore()
    + getInstance(){static}: Giocatore
    + isSconfitto(): boolean
    + applicaDanno(float): void
    + setArma(Arma): void
    + getArma(): Arma
    + getVita(): float
}
show Giocatore members

interface Nemico<<interface>> {
    + getNome(): String
    + applicaDanno(float): void
    + affliggiDanno(): float
    + isSconfitto(): boolean
    + getVita(): float
}
show Nemico members

class Dungeon<<abstract>> {
    - livello: int
    - generaTipo: Map<Integer, TipoNemico>
    + getLivello(): int
    + esplora(): Nemico
    # getNemico(TipoNemico){abstract}: Nemico
}
show Dungeon members

class Bosco extends Dungeon {
    - generaNemico: Map<TipoNemico, Supplier<Nemico>>
    # getNemico(TipoNemico): Nemico
}
show Bosco members

class Deserto extends Dungeon {
    - generaNemico: Map<TipoNemico, Supplier<Nemico>>
    # getNemico(TipoNemico): Nemico
}
show Deserto members

class Strega implements Nemico
class Ciclope implements Nemico
class Chimera implements Nemico
class Goblin implements Nemico

'interface StatoPersonaggio<<interface>> {
 '   + mostra(): String
'}
'show StatoPersonaggio members

'class Attacco implements StatoPersonaggio
'class Difesa implements StatoPersonaggio
'class Assalto implements StatoPersonaggio

'interface StatoBattaglia<<interface>> {
'    + Lotta(Battaglia): StatoBattaglia 
'}

'class InizioBattaglia implements StatoBattaglia
'class Sfida implements StatoBattaglia
'class Vittoria implements StatoBattaglia
'class Sconfitta implements StatoBattaglia

GeneraPietra -l-> Pietra
GeneraPietra -d-> PietraGrigia
GeneraPietra -d-> PietraBianca
GeneraPietra -d-> PietraNera
GeneraArma -l-> Arma
GeneraArma -d-> Ascia
GeneraArma -d-> Mannaia
GeneraArma -d-> Spada
GeneraArma -d-> GeneraPietra
GeneraArma -d-> Pietra

Ascia -d-> Pietra
Mannaia -d-> Pietra
Spada -d-> Pietra

Giocatore -r-> Arma
Partita -r-> Giocatore

Partita -r-> GeneraArma

Bosco -u-> Chimera
Bosco -u-> Goblin
Bosco -u-> Strega
Deserto -u-> Chimera
Deserto -u-> Goblin
Deserto -u-> Ciclope
Dungeon -l-> Nemico

Partita -l-> Dungeon
Partita -l-> Nemico

@enduml